[package]
name = "fpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
argh = "0.1.12"
image = "0.24.7"
itertools = "0.12.0"
thiserror = "1.0.50"
